version: '2'
services:
  ui:
    image: robertkitzing/liga-manager-ui
    ports:
      - "80:80"
      - "443:443"
    links:
      - api:api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - api

  api:
    image: mklocke/liga-manager-api
    volumes:
      - /var/www/api
      - ./config/jwt:/var/www/api/config/jwt
    links:
      - mariadb:mariadb
    env_file:
      - ./api/.env
  
  mariadb:
    image: mariadb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./api/.env

  websocket:
    image: robertkitzing/liga-manager-websocket
    ports:
      - "9898:9898"
