version: '2'
services:
  ui:
    image: robertkitzing/liga-manager-ui:3.0.4-149
  api:
    image: mklocke/liga-manager-api:0.7.0
    volumes:
      - /var/www/api
      - /etc/jwt:/etc/jwt
    depends_on:
      - mariadb
      - postfix
      - redis
    env_file:
      - ./api.env 
  mariadb:
    image: mariadb:10.3.7
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    volumes_from:
      - api
      - cms
    depends_on:
      - ui
      - api
      - cms
  postfix:
    image: tozd/postfix
    volumes:
      - /var/spool/postfix:/var/spool/postfix
    environment:
      - MY_NETWORKS=172.18.0.0/16
      - MAILNAME=wildeligabremen.de
  cms:
    image: wordpress:4.9.6-php7.2-fpm-alpine
    volumes:
      - ./volumes/wp-files:/var/www/html
    env_file:
      - ./wordpress.env
    depends_on:
      - mariadb
  redis:
    image: redis:4-alpine
    ports:
      - "127.0.0.1:6379:6379"
