version: '2'
services:
  ui:
    image: robertkitzing/liga-manager-ui:0.2
  api:
    image: mklocke/liga-manager-api
    volumes:
      - /var/www/api
      - ./config/jwt:/etc/jwt
    links:
      - mariadb:mariadb
    env_file:
      - ./api/.env 
  mariadb:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./api/.env
  websocket:
    image: robertkitzing/liga-manager-websocket
    ports:
      - "9898:9898"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.http.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - ui
      - api
    depends_on:
      - websocket
