version: '3'
services:
  ui:
    image: robertkitzing/liga-manager-ui:4.0.0-186
    env_file:
      - ./ui.env
  api:
    image: mklocke/liga-manager-api:1.0.4
    user: www-data
    volumes:
      - api-public:/var/www/api/public
    depends_on:
      - mariadb
      - postfix
      - redis
    env_file:
      - ./api.env 
  mariadb:
    image: mariadb:10.3.12
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
      - api-public:/var/www/api/public:ro
      - ./volumes/wp-files:/var/www/html
    depends_on:
      - ui
      - api
      - cms
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-webroot:/var/www/certbot
      - ./volumes/letsencrypt:/etc/letsencrypt
  postfix:
    image: tozd/postfix
    volumes:
      - ./volumes/postfix:/var/spool/postfix
    environment:
      - MY_NETWORKS=172.19.0.0/16
      - MAILNAME=wildeligabremen.de
  cms:
    image: wordpress:4.9.6-php7.2-fpm-alpine
    volumes:
      - ./volumes/wp-files:/var/www/html
    env_file:
      - ./wordpress.env
    depends_on:
      - mariadb
  redis:
    image: redis:4-alpine
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  api-public:
  certbot-webroot:

