version: '2'
services:
  ui:
    image: robertkitzing/liga-manager-ui:0.4
  api:
    image: mklocke/liga-manager-api:0.2.0
    volumes:
      - /var/www/api
      - /etc/jwt:/etc/jwt
    depends_on:
      - mariadb
      - postfix
    env_file:
      - ./api.env 
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./api.env
  websocket:
    image: robertkitzing/liga-manager-websocket:0.1
    volumes:
      - /etc/letsencrypt/live/wildeligabremen.de:/cert
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    volumes_from:
      - ui
      - api
      - cms
    depends_on:
      - ui
      - api
      - websocket
      - cms
  postfix:
    image: tozd/postfix
    volumes:
      - /var/spool/postfix:/var/spool/postfix
    environment:
      - MY_NETWORKS=172.18.0.0/16
      - MAILNAME=wildeligabremen.de
  cms:
    image: wordpress:4.9.6-php7.2-fpm-alpine
    volumes:
      - ./volumes/wp-files:/var/www/html
    env_file:
      - ./wordpress.env
    depends_on:
      - mariadb
