version: '3'
services:
  ui:
    image: robertkitzing/liga-manager-ui:latest
    env_file:
      - ./ui.env
  api:
    image: mklocke/liga-manager-api:1.6.2
    user: www-data
    volumes:
      - ./import:/var/www/api/import
    depends_on:
      - mariadb
      - redis
    env_file:
      - ./api.env 
  mariadb:
    image: mariadb:10.4
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/letsencrypt:/etc/letsencrypt
      - ./volumes/wp-files:/var/www/html
    depends_on:
      - ui
      - api
      - cms
  cms:
    image: wordpress:5.5-php7.4-fpm-alpine
    volumes:
      - ./volumes/wp-files:/var/www/html
    env_file:
      - ./wordpress.env
    depends_on:
      - mariadb
  redis:
    image: redis:5-alpine
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  mariadb:
