version: '2'
services:
  ui:
    image: robertkitzing/liga-manager-ui
    ports:
      - "80:80"
      - "443:443"
    links:
      - api:api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - api

  api:
    image: mklocke/liga-manager-api
    volumes:
      - /var/www/api
      - ./config/jwt:/var/www/config/jwt
    links:
      - mariadb:mariadb
    env_file:
      - ./api/.env
  
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./api/.env
