version: '3'
services:
  ui:
    image: robertkitzing/liga-manager-ui:4.0.0-191
    env_file:
      - ./ui.env
  api:
    image: mklocke/liga-manager-api:1.2.3
    user: www-data
    volumes:
      - api-public:/var/www/api/public
      - ./import:/var/www/api/import
    depends_on:
      - mariadb
      - redis
    env_file:
      - ./api.env 
  mariadb:
    image: mariadb:10.3.12
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/letsencrypt:/etc/letsencrypt
      - api-public:/var/www/api/public:ro
      - ./volumes/wp-files:/var/www/html
    depends_on:
      - ui
      - api
      - cms
  cms:
    image: wordpress:5.2-php7.3-fpm-alpine
    volumes:
      - ./volumes/wp-files:/var/www/html
    env_file:
      - ./wordpress.env
    depends_on:
      - mariadb
  redis:
    image: redis:4-alpine
    ports:
      - "127.0.0.1:6379:6379"
volumes:
  api-public:

