# This playbook performs a complete deployment
# It will rewrite configuration for all services and recreate all containers if its image or config has been updated
# This will come with be a short downtime
- hosts: wlb-prod-ubu24
  vars_files:
    - secrets/production.yml
    - vars/production.yml

  tasks:
    - name: Write secrets
      copy:
        content: "{{ item.content }}"
        dest: "{{ app_basedir }}/secrets/{{ item.file }}"
      with_items:
        - file: email-password
          content: "{{ email_gateway_password }}"
        - file: jwt-secret
          content: "{{ jwt_secret }}"
        - file: lima-db-password
          content: "{{ db_passwords.lima }}"
        - file: root-db-password
          content: "{{ db_passwords.root }}"
        - file: wordpress-db-password
          content: "{{ db_passwords.wordpress }}"

    - name: Update setup.sql
      template:
        src: conf/setup.sql.j2
        dest: "{{ app_basedir }}/setup.sql"

    - name: Update utility scripts
      template:
        src: "scripts/{{ item }}.j2"
        dest: "{{ app_basedir }}/{{ item }}"
        mode: '0775'
      with_items:
        - backup-lima.sh
        - backup-wordpress.sh
        - certbot-create.sh
        - certbot-renew.sh

    - name: Update config files
      template:
        src: "conf/{{ item }}.j2"
        dest: "{{ app_basedir }}/{{ item }}"
      with_items:
        - docker-compose.yml
        - nginx.conf
        - nginx-ssl.conf
        - php.ini
        - mariadb.cnf
        - wordpress-fpm.conf

    - name: Update services
      community.docker.docker_compose_v2:
        build: always
        pull: always
        project_src: "{{ app_basedir }}"
        services:
          - "{{ item }}"
        state: present
        wait: true
      with_items:
        - redis
        - mariadb
        - api
        - wordpress
        - imgproxy
        - nginx
