# This playbook performs a complete deployment
# It will rewrite configuration for all services and recreate all containers
# Since webserver and database are restarted as well, there will be a short downtime
- hosts: all
  become: true
  vars_files:
    - secrets/production.yml
    - vars/production.yml

  tasks:
    - name: Ensure application basedir is present
      file:
        path: "{{ app_basedir }}"
        state: directory

    - name: Check if docker-compose.yml exists
      stat:
        path: "{{ app_basedir }}/docker-compose.yml"
      register: docker_compose_yml

    - name: Remove running containers
      command: docker compose down
      args:
        chdir: "{{ app_basedir }}"
      when: docker_compose_yml.stat.exists

    - name: Update setup.sql
      template:
        src: conf/setup.sql.j2
        dest: "{{ app_basedir }}/setup.sql"
        owner: root
        group: docker
        mode: '0644'

    - name: Update certbot-create.sh
      template:
        src: scripts/certbot-create.sh.j2
        dest: "{{ app_basedir }}/certbot-create.sh"
        owner: root
        group: docker
        mode: '0755'

    - name: Update config files
      template:
        src: "conf/{{ item }}.j2"
        dest: "{{ app_basedir }}/{{ item }}"
        owner: root
        group: docker
        mode: '0640'
      with_items:
        - docker-compose.yml
        - nginx.conf
        - api.env
        - ui.env
        - wordpress.env
        - my.cnf

    - name: Pull container images
      command: docker compose pull
      args:
        chdir: "{{ app_basedir }}"

    - name: Create containers
      command: docker compose up -d
      args:
        chdir: "{{ app_basedir }}"

    - name: Configure daily cronjobs
      template:
        src: "scripts/{{ item }}.sh.j2"
        dest: "/etc/cron.daily/{{ item }}"
        owner: root
        group: docker
        mode: '0750'
      with_items:
        - certbot-renew
        - backup
