# This playbook performs a complete deployment
# It will rewrite configuration for all services and recreate all containers
# Since webserver and database are restarted as well, there will be a short downtime
- hosts: wlb-prod-02
  become: true
  vars_files:
    - secrets/production.yml
    - vars/production.yml

  tasks:
    - name: Ensure application basedir is present
      file:
        path: "{{ app_basedir }}"
        state: directory

    - name: Update setup.sql
      template:
        src: conf/setup.sql.j2
        dest: "{{ app_basedir }}/setup.sql"
        owner: root
        group: docker
        mode: '0644'

    - name: Copy backup scripts
      copy:
        src: "scripts/{{ item }}"
        dest: "{{ app_basedir }}/{{ item }}"
        owner: root
        group: docker
        mode: '0755'
      with_items:
        - backup-lima.sh
        - backup-wordpress.sh

    - name: Update utility scripts
      template:
        src: "scripts/{{ item }}.j2"
        dest: "{{ app_basedir }}/{{ item }}"
        owner: root
        group: docker
        mode: '0755'
      with_items:
        - certbot-create.sh
        - certbot-renew.sh

    - name: Update config files
      template:
        src: "conf/{{ item }}.j2"
        dest: "{{ app_basedir }}/{{ item }}"
        owner: root
        group: docker
        mode: '0640'
      with_items:
        - docker-compose.yml
        - nginx.conf
        - nginx-ssl.conf
        - api.env
        - ui.env
        - wordpress.env
        - my.cnf

    - name: Pull container images
      command: docker compose pull
      args:
        chdir: "{{ app_basedir }}"

    - name: Create new containers
      command: docker compose up -d
      args:
        chdir: "{{ app_basedir }}"

    - name: Copy systemd unit files
      copy:
        src: "conf/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - backup-lima.service
        - backup-lima.timer
        - backup-wordpress.service
        - backup-wordpress.timer
        - certbot-renew.service
        - certbot-renew.timer

    - name: Reload systemd
      command: "systemctl daemon-reload"

    - name: Enable systemd units
      command: "systemctl enable {{ item }}"
      with_items:
        - backup-lima.service
        - backup-lima.timer
        - backup-wordpress.service
        - backup-wordpress.timer
        #- certbot-renew.service
        #- certbot-renew.timer
