# This playbook performs a complete deployment
# It will rewrite configuration for all services and recreate all containers if its image or config has been updated
# This will come with be a short downtime
- name: Deploy containers
  hosts: wlb-prod-ubu26
  vars_files:
    - secrets/production.yml
    - vars/production.yml

  tasks:
    - name: Ensure secrets directory exists
      file:
        path: "/usr/local/secrets"
        state: directory
        mode: '0755'

    - name: Write secrets
      copy:
        content: "{{ item.content }}"
        dest: "/usr/local/secrets/{{ item.file }}"
        mode: '0644'
      with_items:
        - file: email-password
          content: "{{ email_gateway_password }}"
        - file: jwt-secret
          content: "{{ jwt_secret }}"
        - file: lima-db-password
          content: "{{ db_passwords.lima }}"
        - file: root-db-password
          content: "{{ db_passwords.root }}"
        - file: wordpress-db-password
          content: "{{ db_passwords.wordpress }}"
        - file: exporter-db-password
          content: "{{ db_passwords.exporter }}"

    - name: Update setup.sql
      template:
        src: conf/setup.sql.j2
        dest: "/usr/local/etc/setup.sql"
        mode: '0644'

    - name: Update utility scripts
      template:
        src: "scripts/{{ item }}.sh.j2"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0775'
      with_items:
        - backup-lima
        - backup-wordpress
        - certbot-create
        - certbot-renew
        - docker-sendmail

    - name: Update config files
      template:
        src: "conf/{{ item }}.j2"
        dest: "/usr/local/etc/{{ item }}"
        mode: '0644'
      with_items:
        - docker-compose.yml
        - nginx.conf
        - nginx-ssl.conf
        - php.ini
        - mariadb.cnf
        - wordpress-fpm.conf
