# Migrate volumes from one host to another
- hosts: wlb-test-ubu24
  become: true

  tasks:
    - name: Migrate volumes
      synchronize:
        src: {{ item }}/
        dest: {{ item }}/
        archive: true
        delete: true
      delegate_to: wlb-prod-ubu24
      with_items:
        - {{ volumes.certs.path }}
        - {{ volumes.logos.path }}
        - {{ volumes.mariadb.path }}
        - {{ volumes.wp-files.path }}
