# This playbook performs a rolling upgrade deployment
# It is only suitable for updating main application services (api/ui) without changing config files
# Do not use this if updates to the webserver or the database need to be applied
- hosts: wlb-prod-01
  become: true
  vars_files:
    - vars/production.yml

  tasks:
    - name: Update docker-compose.yml
      template:
        src: "conf/docker-compose.yml.j2"
        dest: "{{ app_basedir }}/docker-compose.yml"
        owner: root
        group: docker
        mode: '0640'

    - name: Pull container images
      command: docker compose pull api ui
      args:
        chdir: "{{ app_basedir }}"

    - name: Recreate containers with updated images
      command: docker compose up -d api ui
      args:
        chdir: "{{ app_basedir }}"
