- hosts: all
  become: true
  vars_files:
    - vars/default.yml
    - vars/production.yml

  tasks:
    - name: Make sure we have a 'docker' group
      group:
        name: docker
        state: present

    - name: Make sure users are present
      user:
        name: "{{ item }}"
        groups: docker
      with_items: "{{ docker_users }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Add GPG keys for apt repositories
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Configure apt repositories
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install packages
      apt: name={{ sys_packages }} state=latest
