# This playbook contains setup steps to be applied on new servers
- hosts: all
  become: true
  vars_files:
    - vars/production.yml

  tasks:
    - name: Make sure we have a 'docker' group
      group:
        name: docker
        state: present

    - name: Make sure users are present
      user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: docker
        append: yes
      with_items: "{{ docker_users }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Add GPG keys for apt repositories
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Configure apt repositories
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache
      apt: update_cache=yes

    - name: Install packages
      apt: name={{ sys_packages }} state=latest

    - name: Make sure docker plugin path exists
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: "0755"

    - name: Download docker-compose as plugin from GitHub
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: "0755"
