# This playbook upgrades packages using "apt" and reboots the host if required
- hosts: wlb-prod-01
  become: true

  tasks:
    - name: Perform a safe upgrade of installed packages
      apt:
        upgrade: safe
        update_cache: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required)
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
