type: "host_metrics"
scrape_interval_secs: 60
collectors: [cpu, cgroups, disk, filesystem, load, host, memory, network]
cgroups:
  groups:
    excludes:
      - "*.mount"
      - "system.slice/*.mount"
      - "user.slice/*.mount"
filesystem:
  filesystems:
    includes:
      - "ext4"
      - "vfat"
    excludes:
      - "overlay"
      - "nsfs"
      - "binfmt_misc"