[updates]
strategy = "periodic"

[updates.periodic]
time_zone = "Etc/UTC"

[[updates.periodic.window]]
days = [ "Mon" ]
start_time = "04:30"
length_minutes = 30

[agent.timing]
steady_interval_secs = 3600
